### ISSUE TITLE
Close PR when pattern matches

### ISSUE THREAD

**Issue by HasanHajHasan** [xalvarez/prevent-file-change-action#1064]
Adding an option to close PR in case if there is a matching pattern instead failing the PR

**Comment by xalvarez** [comment]
Hi @HasanHajHasan sure, it could be added as an optional option that defaults to false. Is this something you would like to work on?

**Comment by HasanHajHasan** [comment]
I can open a PR for it

**Comment by HasanHajHasan** [comment]
Do i need permission to push a feature branch ?

**Comment by xalvarez** [comment]
Hello, no, you need to issue a pull request from a fork.

**Comment by xalvarez** [comment]
This has been included in version 1.9.0.- Thanks again for your contribution @HasanHajHasan!
