### ISSUE TITLE
Document required permissions for GITHUB_TOKEN

### ISSUE THREAD

**Issue by kevinpapst** [xalvarez/prevent-file-change-action#485]
Hi @xalvarez , 

this is just another tiny request, but not feature wise but for documentation.
I wanted to introduce your action to more repositories. 

As you need a GITHUB_TOKEN for the workflow, it would be nice to build trust by documenting which exact permissions are required: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

According to my check the only place where it is used is to read the list of all files changed in the PR:
https://github.com/xalvarez/prevent-file-change-action/blob/main/src/github-service.ts#L16
And probably the line to fail the job:
https://github.com/xalvarez/prevent-file-change-action/blob/main/src/main.ts#L29

The default `permissive` permission set is rather dangerous:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

So my request is: can you document the which permissions are exactly required for the Github token?

E.g.
```
permissions:
  contents: read
  pull-requests: read
```

And include those in the example in the README?

**Comment by xalvarez** [comment]
Good idea, thanks for the feedback :slightly_smiling_face: I'll take care of this soon.

**Comment by xalvarez** [comment]
Hi @kevinpapst, I've already added the documentation.
Failing the job doesn't require any additional permissions.
