### ISSUE TITLE
Allow running on `push` event

### ISSUE THREAD

**Issue by harryzcy** [xalvarez/prevent-file-change-action#781]
**Is your feature request related to a problem? Please describe.**

When trying to run the workflow on `push` event, it gives the error saying only pull_request is supported.

**Describe the solution you'd like**

Can you also allow running it on push? Since a push event will also have changed files.

**Describe alternatives you've considered**

**Additional context**

**Comment by xalvarez** [comment]
Hi @harryzcy, sounds good. At the moment I don't have much time to work on this project. I can work on it whenever I find some time, or someone else may issue a pull request for it.

**Comment by harryzcy** [comment]
@xalvarez Cool. I just created a PR
